const booking = {
  GET_BOOKING_SUCCESS: "GET_BOOKING_SUCCESS",
  GET_BOOKING_ERROR: "GET_BOOKING_ERROR",
  GET_BOOKING_REQUEST: "GET_BOOKING_REQUEST",

  UPDATE_BOOKING_SUCCESS: "UPDATE_BOOKING_SUCCESS",
  UPDATE_BOOKING_ERROR: "UPDATE_BOOKING_ERROR",
  UPDATE_BOOKING_REQUEST: "UPDATE_BOOKING_REQUEST",
  UPDATE_BOOKING_DATA: "UPDATE_BOOKING_DATA",

  ADD_BOOKING_SUCCESS: "ADD_BOOKING_SUCCESS",
  ADD_BOOKING_ERROR: "ADD_BOOKING_ERROR",
  ADD_BOOKING_REQUEST: "ADD_BOOKING_REQUEST",

  DELETE_BOOKING_SUCCESS: "DELETE_BOOKING_SUCCESS",
  DELETE_BOOKING_ERROR: "DELETE_BOOKING_ERROR",
  DELETE_BOOKING_REQUEST: "DELETE_BOOKING_REQUEST",

  GET_BOOKING_DETAILS_SUCCESS: "GET_BOOKING_DETAILS_SUCCESS",
  GET_BOOKING_DETAILS_ERROR: "GET_BOOKING_DETAILS_ERROR",
  GET_BOOKING_DETAILS_REQUEST: "GET_BOOKING_DETAILS_REQUEST",

  getBooking: (data) => ({
    type: booking.GET_BOOKING_REQUEST,
    data,
  }),
  updateBookingData: (data) => ({
    type: booking.UPDATE_BOOKING_DATA,
    data,
  }),
  updateBooking: (data, id) => ({
    type: booking.UPDATE_BOOKING_REQUEST,
    data,
    id,
  }),
  deleteBooking: (data) => ({
    type: booking.DELETE_BOOKING_REQUEST,
    data,
  }),
  getBookingDetails: (id) => ({
    type: booking.GET_BOOKING_DETAILS_REQUEST,
    id,
  }),
  addBooking: (data) => ({
    type: booking.ADD_BOOKING_REQUEST,
    data,
  }),
};

export default booking;
