const tickets = {
  GET_TICKETS_SUCCESS: "GET_TICKETS_SUCCESS",
  GET_TICKETS_ERROR: "GET_TICKETS_ERROR",
  GET_TICKETS_REQUEST: "GET_TICKETS_REQUEST",

  UPDATE_TICKETS_SUCCESS: "UPDATE_TICKETS_SUCCESS",
  UPDATE_TICKETS_ERROR: "UPDATE_TICKETS_ERROR",
  UPDATE_TICKETS_REQUEST: "UPDATE_TICKETS_REQUEST",
  UPDATE_TICKET_DATA: "UPDATE_TICKET_DATA",

  ADD_TICKETS_SUCCESS: "ADD_TICKETS_SUCCESS",
  ADD_TICKETS_ERROR: "ADD_TICKETS_ERROR",
  ADD_TICKETS_REQUEST: "ADD_TICKETS_REQUEST",

  DELETE_TICKETS_SUCCESS: "DELETE_TICKETS_SUCCESS",
  DELETE_TICKETS_ERROR: "DELETE_TICKETS_ERROR",
  DELETE_TICKETS_REQUEST: "DELETE_TICKETS_REQUEST",

  GET_TICKET_DETAILS_SUCCESS: "GET_TICKET_DETAILS_SUCCESS",
  GET_TICKET_DETAILS_ERROR: "GET_TICKET_DETAILS_ERROR",
  GET_TICKET_DETAILS_REQUEST: "GET_TICKET_DETAILS_REQUEST",

  getTickets: (data) => ({
    type: tickets.GET_TICKETS_REQUEST,
    data,
  }),
  updateTickets: (data) => ({
    type: tickets.UPDATE_TICKETS_REQUEST,
    data,
  }),
  addTickets: (data) => ({
    type: tickets.ADD_TICKETS_REQUEST,
    data,
  }),
  deleteTickets: (data) => ({
    type: tickets.DELETE_TICKETS_REQUEST,
    data,
  }),
  getTicketDetails: (data) => ({
    type: tickets.GET_TICKET_DETAILS_REQUEST,
    data,
  }),
  ticketUpdateData: (data) => ({
    type: tickets.UPDATE_TICKET_DATA,
    data,
  }),
};

export default tickets;
